---
- name: RHV Block
  block:
    - name: Login to RHV
      redhat.rhv.ovirt_auth:
        hostname: "{{ rhvm_fqdn }}"
        username: "{{ rhvm_user }}"
        password: "{{ rhvm_password }}"
        ca_file: "{{ rhvm_cafile | default(omit) }}"
        insecure: "{{ rhvm_insecure | default(true) }}"
      delegate_to: localhost
      run_once: true

    - name: Pull snapshot ID for a VM
      redhat.rhv.ovirt_snapshot_info:
        auth: "{{ ovirt_auth }}"
        vm: "{{ inventory_hostname }}"
        description: "{{ description }}"
      register: snapshot
      delegate_to: localhost

    - name: Remove Snapshot on VM(s)
      redhat.rhv.ovirt_snapshot:
        auth: "{{ ovirt_auth }}"
        vm_name: "{{ inventory_hostname }}"
        snapshot_id: "{{ snapshot.ovirt_snapshots[0].id }}"
        state: absent
      register: snapshot
      delegate_to: localhost

  always:
    - name: Logout from RHV
      redhat.rhv.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      delegate_to: localhost
      run_once: true
