---
- name: Perform inital configs of lab VMs
  hosts: "{{ vm_name | default('all')}}"
  strategy: free
  gather_facts: false

  pre_tasks:
    - name: Set facts for ansible_host to work with IP addr
      ansible.builtin.set_fact:
        ansible_host: "{{ ip_addr }}"
      delegate_to: localhost

    - name: Wait for connection on AWS
      ansible.builtin.wait_for_connection:
        timeout: 900
      when: shadowman_provision_hypervisor | default('RHV') == "AWS"

    - name: Gather facts to work with remainder of playbook
      ansible.builtin.setup:

  tasks:
    - name: Linux Setup
      ansible.builtin.include_role:
        name: shadowman_linux_setup
      when: ansible_os_family is match("RedHat")

    - name: RHEL register
      ansible.builtin.include_role:
        name: shadowman_rhel_register
      when: ansible_os_family is match("RedHat")

    - name: IDM register
      ansible.builtin.include_role:
        name: shadowman_add_to_idm
      when:
        - ansible_os_family is match("RedHat")
        - shadowman_provision_hypervisor|default('RHV') != "Azure"
        - shadowman_provision_hypervisor|default('RHV') != "AWS"

    - name: Windows Config
      ansible.builtin.include_role:
        name: shadowman_add_to_ad
      when:
        - ansible_os_family is match("Windows")
        - shadowman_provision_hypervisor|default('RHV') != "Azure"
        - shadowman_provision_hypervisor|default('RHV') != "AWS"
