---
- name: RHEL PCI Compliance
  hosts: all
  strategy: free

  tasks:
    - name: PCI Compliance RHEL7
      ansible.builtin.include_role:
        name: shadowman_pci_rhel7
      when: os is match(".*7.*")

    - name: PCI Compliance RHEL8
      ansible.builtin.include_role:
        name: shadowman_pci_rhel8
      when: os is match(".*8.*")
