---
- name: Build Tags Report
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get VM info
      ansible.builtin.include_role:
        name: shadowman_gather_tags

    - name: Build report
      ansible.builtin.include_role:
        name: shadowman.reports.build_report_tags
        apply:
          delegate_to: report.shadowman.dev
          run_once: true
