---
- name: Add Fancy Legal Disclaimer (MOTD)
  ansible.builtin.copy:
    src: templates/add_motd
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"

- name: Set timezone
  community.general.timezone:
    name: America/New_York
