---
- name: Install Katello RPM for Satellite Server for RHEL 7
  ansible.builtin.yum:
    name: https://sat6.shadowman.dev/pub/katello-ca-consumer-latest.noarch.rpm
    state: present
    disable_gpg_check: true
  when:
    - ansible_pkg_mgr == "yum"
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"

- name: Install Katello RPM for Satellite Server for RHEL 8 or 9
  ansible.builtin.dnf:
    name: https://sat6.shadowman.dev/pub/katello-ca-consumer-latest.noarch.rpm
    state: present
    disable_gpg_check: true
  when:
    - ansible_pkg_mgr == "dnf"
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"

- name: Use Activation Key to Register RHEL7 Machine to Satellite
  community.general.redhat_subscription:
    state: present
    activationkey: RHEL7
    org_id: Shadowman
  when:
    - ansible_distribution_version is match("7.*")
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"
  ignore_errors: true

- name: Use Activation Key to Register RHEL8 Machine to Satellite
  community.general.redhat_subscription:
    state: present
    activationkey: RHEL8
    org_id: Shadowman
  when:
    - ansible_distribution_version is match("8.*")
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"
  ignore_errors: true

- name: Use Activation Key to Register RHEL9 Machine to Satellite
  community.general.redhat_subscription:
    state: present
    activationkey: RHEL9
    org_id: Shadowman
  when:
    - ansible_distribution_version is match("9.*")
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"
  ignore_errors: true

- name: Use Activation Key to Register Azure RHEL Machine to RHSM
  community.general.redhat_subscription:
    state: present
    activationkey: azure
    org_id: "13247185"
  when: shadowman_provision_hypervisor | default('RHV') == "Azure"
  ignore_errors: true

- name: Enable Repositories for RHEL 7
  community.general.rhsm_repository:
    name:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-optional-rpms
    purge: true
  when:
    - ansible_distribution_version is match("7.*")
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"

- name: Enable Repositories for RHEL 8 when not using Azure base image
  community.general.rhsm_repository:
    name:
      - rhel-8-for-x86_64-appstream-rpms
      - rhel-8-for-x86_64-baseos-rpms
    purge: true
  when:
    - ansible_distribution_version is match("8.*")
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"

- name: Enable Repositories for RHEL 9 when not using Azure base image
  community.general.rhsm_repository:
    name:
      - rhel-9-for-x86_64-appstream-rpms
      - rhel-9-for-x86_64-baseos-rpms
    purge: true
  when:
    - ansible_distribution_version is match("9.*")
    - shadowman_provision_hypervisor|default('RHV') != "Azure"
    - shadowman_provision_hypervisor|default('RHV') != "AWS"
