---
- name: Upgrade all packages (dnf)
  ansible.builtin.dnf:
    name: "*"
    state: latest
    exclude: "{{ exclude_packages }}"
    update_only: true

- name: Check to see if we need a reboot
  ansible.builtin.command: needs-restarting -r
  register: result
  changed_when: result.rc == 1
  failed_when: result.rc > 1
  check_mode: false
